# |from condition buy drowown
                                    # ((((df['Low'].shift(6) < df['BBL'].shift(6)) & ((df['Trend'].shift(6) == 'Downtrend') | (df['regime'].shift(6) == 'downtrend')))
                                    #  |((df['Low'].shift(4) < df['BBL'].shift(4)) & ((df['Trend'].shift(4) == 'Downtrend') | (df['regime'].shift(4) == 'downtrend')))
                                    #  |((df['Low'].shift(3) < df['BBL'].shift(3)) & ((df['Trend'].shift(3) == 'Downtrend') | (df['regime'].shift(3) == 'downtrend')))
                                    #  |((df['Low'].shift(5) < df['BBL'].shift(5)) & ((df['Trend'].shift(5) == 'Downtrend') | (df['regime'].shift(5) == 'downtrend'))))
                                    #  & ((df['BBU_Angle_Degree'].rolling(window=6).mean() > 190) | (df['BBU_Angle_Degree'].rolling(window=5).mean() > 190)
                                    #   | (df['BBU_Angle_Degree'].shift(1).rolling(window=6).mean() > 190) | (df['BBU_Angle_Degree'].shift(1).rolling(window=5).mean() > 190))
                                    #  & ((df['BBL_Angle_Degree'].rolling(window=3).mean() < 180) | (df['BBL_Angle_Degree'].rolling(window=4).mean() < 180))
                                    #  & ((df['EMA_Angle_Degree'].rolling(window=3).mean() < 180) | (df['EMA_Angle_Degree'].rolling(window=4).mean() < 180))
                                    #  & (df['Close'] > df['EMA9']) & (df['Close'] > df['BBM'])
                                    #  & (df['Low'] < df['EMA9']) & (df['Low'].shift(1) < df['BBM'].shift(1)) & (df['High'] < df['BBU'])
                                    #  & (((df['Open'].shift(1) < df['EMA9'].shift(1)) | (df['Open'].shift(1) < df['BBM'].shift(1)))
                                    #  | ((df['Low'].shift(1) < df['EMA9'].shift(1)) & (df['Low'].shift(1) < df['BBM'].shift(1))))
                                    #  & (((df['Close'].shift(1) < df['Close']) & (df['Close'].shift(1) >= df['Close'].shift(2)))
                                    #  | ((df['High'].shift(1) < df['High']) & (df['High'].shift(1) >= df['High'].shift(2))))
                                    #  & (df['volume_profile'] == 1) 
                                    #  & ((df['volume_profile'].shift(1) == 1) | ((df['EMA_Angle_Degree'] < 135) & (df['EMA_Angle_Degree'].shift(1) < 150)))
                                    #  & (df['EMA_Angle_Degree'] < 170) & (df['High'].shift(1).rolling(window=4).mean() < df['High'])
                                    #  & (df['BBM_Angle_Degree'].shift(1) > df['BBM_Angle_Degree'])
                                    #  & (df['High'].shift(1) > df['EMA9'].shift(1))
                                    #  & ((df['BBM'].shift(6) > df['EMA9'].shift(6)) | (df['BBM'].shift(5) > df['EMA9'].shift(5)) | (df['BBM'].shift(4) > df['EMA9'].shift(4)))
                                    #  & (((df['High'] >= df['High'].shift(1))) | ((df['High'] >= df['High'].shift(2)))) 
                                    #  & ~(low_bb_width_candle)
                                    # )